repo_name: quangdungluong/deepstream-101
repo_url: https://github.com/quangdungluong/deepstream-101
site_name: deepstream-101 Docs
edit_uri: edit/main/docs/

nav:
  - Getting Started:
      - Quick Start: index.md
      - Installation: install.md
  - DeepStream Python Apps:
      - deepstream-test1: apps/deepstream-test1.md
      - deepstream-test2: apps/deepstream-test2.md
      - deepstream-test3: apps/deepstream-test3.md

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      title: Page contents
  - mdx_truly_sane_lists

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: false
            filters:
              - "!^_"
            members_order: source
            separate_signature: true
          paths: [apps]
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - section-index
  - mkdocs-video
  - include-markdown

theme:
  features:
    - content.action.edit
    - content.tabs.link
    - content.code.annotate
    - content.code.annotations
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - search.share
    - search.highlight
    - search.suggest
  name: material
  custom_dir: docs/theme
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra_css:
  - extra/css/code_select.css
  - assets/pymdownx-extras/extra-fb5a2a1c86.css

extra_javascript:
  - assets/pymdownx-extras/extra-loader-MCFnu0Wd.js

validation:
  absolute_links: warn
  omitted_files: warn
  unrecognized_links: warn
